name    'mariadb-client'
version '0.0.1'
source 'UNKNOWN'
author 'cup'
license 'Apache License, Version 2.4'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
