#!/usr/bin/perl
#

use DBI;
use MIME::Lite;
use POSIX qw(strftime);
use File::Temp qw/ tempfile tempdir /;

my $host = "127.0.0.1";
my $db = "cms_concrete_db2012";
my $db_username = "wmp_backup";
my $db_password = "yaeHo3AikiNg4ohtoo2o";
my $sender = 'noreply@cambridge.org';
my $recipient = 'rdwood@cambridge.org';
my $cc = 'vsharland@cambridge.org, vpickett@cambridge.org, cvenditti@cambridge.org, lramos@cambridge.org, madlawan@cambridge.org, adudman@cambridge.org';

my $query = <<QUERYEND;
select date_format(DateAdded, '%d/%m/%Y')as dateadded, title, first_name, last_name, uEmail as email, job_title, affiliation as institution, country_code as country, subjects, journals from 
(   select * from (
        SELECT  aa.date_subscribed as DateAdded, aa.job_title as job_title, aa.affiliation as affiliation, aa.email as email, aa.subjects as subjects, aa.journals as journals
        FROM academic_alerts aa
        WHERE aa.date_subscribed > DATE(DATE_SUB(NOW(), INTERVAL 1 DAY))
        AND aa.subjects != "Libalerts"
        ORDER BY aa.date_subscribed ASC
    ) as a
    LEFT JOIN Users u on u.uEmail = a.email
    LEFT JOIN (
        SELECT ak.akID, uav.uID as uIDc, uav.avID
        FROM AttributeKeys ak
        INNER JOIN AttributeKeyCategories akc ON ak.akCategoryID = akc.akCategoryID
        LEFT JOIN UserAttributeValues uav ON uav.akID = ak.akID
        LEFT JOIN atDefault atdb ON uav.avID = atdb.avID
        LEFT JOIN AttributeValues atv ON atv.avID = atdb.avID
        WHERE ak.akHandle IN ('alerts_subscriber') AND akc.akCategoryHandle = 'user'
    ) as c on u.uID = c.uIDc
    LEFT JOIN (
        SELECT uav.uID as uavID3 , atdb.value as first_name
        FROM AttributeKeys ak 
        INNER JOIN AttributeKeyCategories akc ON ak.akCategoryID = akc.akCategoryID
        LEFT JOIN UserAttributeValues uav ON uav.akID = ak.akID
        LEFT JOIN atDefault atdb ON uav.avID = atdb.avID
        WHERE ak.akHandle IN ('first_name')
        AND akc.akCategoryHandle = 'user'
    ) as b on b.uavID3 = c.uIDc
    LEFT JOIN (
        SELECT uav.uID as uavID , atdb.value as last_name
        FROM AttributeKeys ak
        INNER JOIN AttributeKeyCategories akc ON ak.akCategoryID = akc.akCategoryID
        LEFT JOIN UserAttributeValues uav ON uav.akID = ak.akID
        LEFT JOIN atDefault atdb ON uav.avID = atdb.avID
        WHERE ak.akHandle IN ('last_name')
        AND akc.akCategoryHandle = 'user'
    ) as d on d.uavID = c.uIDc
    LEFT JOIN (
        SELECT ats.value as title, uav.uID as userID, uav.avID as uavID2
        FROM AttributeKeys ak
        INNER JOIN AttributeKeyCategories akc ON ak.akCategoryID = akc.akCategoryID
        LEFT JOIN UserAttributeValues uav ON uav.akID = ak.akID
        LEFT JOIN atSelectOptionsSelected atss ON uav.avID = atss.avID
        LEFT JOIN atSelectOptions ats ON atss.atSelectOptionID = ats.ID
        WHERE ak.akHandle IN ('title') AND akc.akCategoryHandle = 'user'
    ) as g on g.userID = c.uIDc
    LEFT JOIN (
        SELECT atdb.value as country_code, uav.uID as userIDC
        FROM AttributeKeys ak
        INNER JOIN AttributeKeyCategories akc ON ak.akCategoryID = akc.akCategoryID
        LEFT JOIN UserAttributeValues uav ON uav.akID = ak.akID
        LEFT JOIN atDefault atdb ON uav.avID = atdb.avID
        WHERE ak.akHandle IN ('country') AND akc.akCategoryHandle = 'user'
    ) as h on h.userIDC = c.uIDc
    
) as d
QUERYEND

# Connect and execute query
my $mysql_dbh = DBI->connect("DBI:mysql:$db:$host", $db_username, $db_password) or die "Failed to connect to db!";

my $mysql_sth = $mysql_dbh->prepare($query);
$mysql_sth->execute();

# Create a temporary CSV file
my ($fh, $filename) = tempfile("reportXXXXXXXXX", UNLINK => 1);
print $fh '"dateadded","title","first_name","last_name","uEmail","job_title","institution","country_code","subjects"', "\n";
while (my @row = $mysql_sth->fetchrow_array()) {
   print $fh  join(',', map {qq("$_")} @row), "\n";
}

# Send file as attachment
my $today = strftime("%Y-%m-%d", localtime);
my $msg = MIME::Lite->new(
    From    => $sender,
    To      => $recipient,
    Cc      => $cc,
    Subject => "Alerts user report for $today",
    Type    => 'multipart/mixed',
);

$msg->attach(
    Type     => 'TEXT',
    Data     => "Hello, this is the WMP Alerts user report for $today.\n\n\n",
);

$msg->attach(
    Encoding => 'base64',
    Disposition => 'attachment',
    Type     => 'text/csv',
    Path     => $filename,
    Filename => "alerts_report_daily-$today.csv",
);

$msg->send;
