#!/bin/sh
#
# glusterd   Startup script for the glusterfs server
#
# chkconfig:   - 20 80
# description: Clustered file-system server

### BEGIN INIT INFO
# Provides: glusterd
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Should-Start: 
# Should-Stop: 
# Default-Start: 
# Default-Stop: 0 1 2 3 4 5 6
# Short-Description: glusterfs server
# Description:       Clustered file-system server
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exe="/usr/sbin/glusterd"
prog="glusterd"

# Fedora File System Layout dictates /run
[ -e /run ] && RUNDIR="/run"
pidf="${RUNDIR:-/var/run}/$prog.pid"

# Set defaults, then source config for eventual overrides
GLUSTERD_NOFILE="65536"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $exe ] || exit 5
    ulimit -n $GLUSTERD_NOFILE
    echo -n $"Starting $prog: "
    daemon $exe${GLUSTERD_LOGFILE+" -l $GLUSTERD_LOGFILE"}${GLUSTERD_LOGLEVEL+" -L $GLUSTERD_LOGLEVEL"} -p $pidf
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    /usr/local/bin/rr-update.sh add > /dev/null
    return $retval
}

stop() {
    /usr/local/bin/rr-update.sh remove > /dev/null
    echo -n $"Stopping $prog: "
    killproc $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status &>/dev/null
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?

